settings:
  first-join-trajectory: firstjoin
  first-join-enable:     true
  first-join-delay:      20
  logging:
    player-start-stop:    true
    player-point-reached: true
internal:
  version: 3
