settings:
  first-join-trajectory: 'firstjoin'
  first-join-enable:     true
  first-join-delay:      20
  language: 'english'
  logging:
    player-start-stop:    true
    player-point-reached: false
  require-permissions-for-signs: false
internal:
  version: 4
