name:    ${project.artifactId}
main:    ${project.groupId}.${project.artifactId}.BukkitPluginMain
version: ${project.version}
website: ${project.url}
author:  SimSonic
load:    POSTWORLD

softdepend:
- ProtocolLib
- PlaceholderAPI
- NoCheatPlus
- HolographicDisplays

commands:
  rscfjd:
    aliases: [fjd]
    description: ${project.artifactId} command hub
    usage: /<command> do what?

permissions:
  rscfjd.admin:
    description: Access to all functions
    default: op
  rscfjd.sign.*:
    description: Ability to use all signs with trajectories
    default: op
